stages:
  - build
  - compress

build:
  stage: build
  before_script:
    - alias ruby=ruby25
    - alias gem=gem25
    - ruby --version
    - gem install asciidoctor -v 1.5.8
    - gem install asciidoctor-pdf --pre
    - gem install rouge
  script:
    - bash buildscript/main.sh --pdf

compress:
  stage: compress
  dependencies:
    - build
  before_script:
    - alias ruby=ruby25
    - alias gem=gem25
    - gem install hexapdf
  script:
    - hexapdf optimize --compress-pages index.pdf documentation.pdf
  artifacts:
    paths:
      - documentation.pdf
    expire_in: 1 mos