stages:
  - build
  - compress

build:
  stage: build
  before_script:
    - ruby25 --version
    - gem25 install asciidoctor -v 1.5.8
    - gem25 install asciidoctor-pdf --pre
    - gem25 install rouge
  script:
    - alias ruby=ruby25; bash buildscript/main.sh --pdf

compress:
  stage: compress
  dependencies:
    - build
  before_script:
    - gem25 install hexapdf
  script:
    - hexapdf optimize --compress-pages index.pdf documentation.pdf
  artifacts:
    paths:
      - documentation.pdf
    expire_in: 1 mos