language: php
php: 7.2
git:
  depth: false
before_script:
- INIT_DIR=$(pwd)
- cd /home/travis/build/
- echo | pecl install channel://pecl.php.net/yaml-2.0.2
- git clone https://github.com/krakjoe/pthreads.git
- cd pthreads
- git checkout 6c6b15138c923b69cfa46ee05fc2dd45da587287
- phpize
- "./configure && make && make install"
- cd ..
- echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- cd ${INIT_DIR}
- bash buildscripts/asciidoc/create_mermaid_config.sh
install:
- gem install asciidoctor -v 1.5.8
- gem install asciidoctor-diagram -v 1.5.14
- gem install asciidoctor-pdf --pre
- gem install rouge
- gem install concurrent-ruby
- npm install -g inline-source-cli
- npm install --save cheerio
- npm install --save lunr
- npm install --save asciidoctor.js
- npm install --save minimist
- npm install -g mermaid.cli
script:
- travis_wait bash buildscripts/build.sh
deploy:
- provider: s3
  access_key_id: "$S3ACCESSID"
  secret_access_key: "$S3ACCESSKEY"
  bucket: wirecard-docs-internal
  region: eu-central-1
  skip_cleanup: true
  local-dir: build/html
  on:
    branch: staging
- provider: s3
  access_key_id: "$S3ACCESSID"
  secret_access_key: "$S3ACCESSKEY"
  bucket: wirecard-docs
  region: eu-central-1
  skip_cleanup: true
  local-dir: build/html
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: ipSdDuEQIwRt6vnJ4t8yIhgRVI2kkaaeOcjIzO4o12vFs3UIVuL9HKv6NfkTgYtt0kmge5iMppdUAQQ3WfGfpEAbljgtAPXnPt40TWzz5DFgSryEEFfOpmIPRhDRumUELGKQzn2vEErsYLGtYO+aet80+/FUPtylOxp+SLyNk4dNmRjK/y7sFH4UCbOFRRDJWDU2PDoOM59eQAhlfNBSuv7jQyK3Yzv3IuQWIAvAnBCrMsNOfAwE73Uc6ufp0hcEZr3x7cY5/SBTW307pjwWw1b40iMRdSp841hPjxo5q2doQ3mLJs4O9BVOUvy0c6Gk6tmYO+5jrV3hoOEUC42HzAa00pkOoIqIBQCI88s/90IXao2Y251T1yJ7XzdQrB1Db4Sx514j1WKLFkV7iKkZ0Gp1NJRrWYEpL8oMbRjzh3JJ60mZYNhaagrEQYRGExNDJB0KXksB+8xJ8zAurzgS6hiEXZL1Ia0sBSh/oJEMJN7li46VERDpGX4rPyx8eZRXdgqnmtfKINYyIVT+tARMLJQkkzjfoj+s69o3MXJFQ08H0EMEgWgHHrgV8vVxoczocf6xv9i5E/gulKp6uvNagh17yLCk8JSCGtAKv3CIyZSikFO/xB5pXGswTWBQ6oTLbRcBrobKav3A2eWGJzNnNY1zpqVBmPC4TPZDvpTYi9I=
    on_success: always
