language: php
php: 7.2
git:
  depth: false
before_script:
- INIT_DIR=$(pwd)
install:
- gem install asciidoctor -v 1.5.8
script:
- echo "Test Me"

notifications:
  slack:
    secure: nNElTLEVjGHWpG1kH4TLetaDld7fKiIIGE/MW7F/Ezpt76bj+ZgqfK0GHeRzy4MWgrE7SDVEv9NYmuvEXa3j0JWG2XmtTyukz/CsKP99X+zOKLUCRiWN3bNutQIZyISM1xEVi+IVSxAn5HsAaGRN9kpKe4svpBB0/b6ymfWXX0Gz2v7bkPNPfdh9HZjMTBT9Eg6oDER6vNqjDeztwq1zkEQ8Hram2YcQs6q7yhrPwIMQxRfAbyheAFxi0brToO2OE4fwg/nwm8q3qWXUak7MV96JZanCod/8DOjtsBSJjqt/0FivkYS92dxeVoDCzGVqpo7++AEMgPimR/gPdl4o4zNzcyHyCT85AZO0XIqwVCJCkr1/5uQhqOH0f4AIedHTV+FRVHBd/qx1ws5X9w2lGl8IRiu/6HUEZQZ9yzYSqvKnpnX/zUK1+9iX4q4pPI4s/nJRks+bn0iOzYX38Zr3qtNTVDFW5Xqm0qyOLFYg73UfJFwgnhK6ndC/opTiWHAA6Ds1nPcXr2UnqHrhFGrxzfjd6r3UrXDgCsIYZOntk5q32EqQ0SbI+mzQeN0QSksELdPqoiXcfze4aPoy4vsGWtrfy8HPkWZGiAtlmzVWx8FzRgT8FMFo8D00wVHHTxFm0GDvflpwW3n2frlK4ZL+6GOHgCiGJKrJ0uphyYZ6/MI=
