language: php
php: 7.2
git:
  depth: false
before_script:
- INIT_DIR=$(pwd)
install:
- gem install asciidoctor -v 1.5.8
script:
- echo "Test Me"
notifications:
  slack:
    on_success: always
    rooms:
      secure: zaS3PJ5bEeLymOMXFQzY40yqNWOHOfPU93BT4pT5ttO72jxbKDVVVTIKj7ypnx1jJXFVCjdprj/H1JCCQ7Ue0H9XzT8N8m+9Pq1a5L6XQLecA1A2frlP5xd5jbbks0FOe+bu2xxRdqAh8dtlWQQSLQRZwrg3lFbNZZCLs/irmwud6Xw4OAeeRaHoepeC4H2kfEK0wa16maCmIXCOoA1PiSzApWyr+d1tnYVQmaDu1EmERsJ+fI+EVEx+fubOZCckYm04SncKO1W2Mk763Qx1okJjR9Ywhqw2ftOTIeSGjsNF5OQeQOF7FLB0p3JFdYXQG3x2MuoErR3JyD7I4a2R3WksdOIi3AkfS/OsSKjq4XcHmbpShPLeqXvXfYHkCoFDVWUiqFNEQPHW3/eSYAZhPevgKToqGtTGDlbnVlxlTqlhzDq30Oxn+0imbpz0wnUXm0qa+7OmdNCnIsnynihM/QHXRzVer4MD6GZ+Ah2Om9dHc8Ux/XOV7XZIHiZRbKbZRvvM2gw7SM+uEShUMsQdG/iE2vScUq2BZ3vcdHKwZZF/R0exsUbl9Gj1lJQy1UgqiveSFpK5QTrdogNwk31duvUkIXFVI+hTOIm+Je1AwpJxWanjOsO/Ghwo1GdgdlGDOPJHVFf5uZiGjrR6hqdM5kOuKSeQD/BuAAZxcprIf20=
