language: php
php: 7.2
env:
  - TRAVIS_ENVSET_FILE="/tmp/set-deploy-env-vars"

matrix:
  include:
    - env: PARTNER=WD
    - env: PARTNER=PO
    - env: PARTNER=MS

before_script:
  - INIT_DIR=$(pwd)
  - cd /home/travis/build/
  - echo | pecl install channel://pecl.php.net/yaml-2.0.2
  - git clone https://github.com/krakjoe/pthreads.git
  - cd pthreads
  - git checkout 6c6b15138c923b69cfa46ee05fc2dd45da587287
  - phpize
  - ./configure && make && make install
  - cd ..
  - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ${INIT_DIR}
install:
  - gem install asciidoctor -v 1.5.8
  - gem install asciidoctor-diagram -v 1.5.14
  - gem install asciidoctor-pdf --pre
  - gem install rouge
  - gem install concurrent-ruby
  - npm install -g inline-source-cli
  - npm install --save cheerio
  - npm install --save lunr
  - npm install --save asciidoctor.js
  - npm install --save minimist
script:
  - chmod +x buildscripts/main.sh
  - ./buildscripts/main.sh
  - for p in $(cat ${TRAVIS_ENVSET_FILE}); do export DEPLOY_${p}=TRUE; done
before_deploy:
  - echo "in before_deploy section beginning " ${DEPLOY_PO}
deploy:
  - provider: s3
    access_key_id: $S3ACCESSID
    secret_access_key: $S3ACCESSKEY
    bucket: wirecard-docs-internal
    region: eu-central-1
    skip_cleanup: true
    local-dir: ${HOME}/build/WD/html
    on:
      branch: staging
  - provider: s3
    access_key_id: $S3ACCESSID
    secret_access_key: $S3ACCESSKEY
    bucket: wirecard-docs
    region: eu-central-1
    skip_cleanup: true
    local-dir: ${HOME}/build/WD/html
    on:
      branch: master
  - provider: s3
    access_key_id: $S3ACCESSID
    secret_access_key: $S3ACCESSKEY
    bucket: p-bckt-internal
    region: eu-central-1
    skip_cleanup: true
    local-dir: ${HOME}/build/PO/html
    on:
      branch: PSPDOC-662
      condition: $DEPLOY_PO = TRUE
  - provider: s3
    access_key_id: $S3ACCESSID
    secret_access_key: $S3ACCESSKEY
    bucket: p-bckt
    region: eu-central-1
    skip_cleanup: true
    local-dir: ${HOME}/build/PO/html
    on:
      branch: master
      condition: $DEPLOY_PO = TRUE
  - provider: s3
    access_key_id: $S3ACCESSID
    secret_access_key: $S3ACCESSKEY
    bucket: m-bckt-internal
    region: eu-central-1
    skip_cleanup: true
    local-dir: ${HOME}/build/MS/html
    on:
      branch: PSPDOC-662
      condition: $DEPLOY_MS = TRUE
  - provider: s3
    access_key_id: $S3ACCESSID
    secret_access_key: $S3ACCESSKEY
    bucket: m-bckt
    region: eu-central-1
    skip_cleanup: true
    local-dir: ${HOME}/build/MS/html
    on:
      branch: master
      condition: $DEPLOY_MS = TRUE
