language: php
php: 7.2
git:
  depth: false
before_script:
- INIT_DIR=$(pwd)
- cd /home/travis/build/
- echo | pecl install channel://pecl.php.net/yaml-2.0.2
- git clone https://github.com/krakjoe/pthreads.git
- cd pthreads
- git checkout 6c6b15138c923b69cfa46ee05fc2dd45da587287
- phpize
- "./configure && make && make install"
- cd ..
- echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- cd ${INIT_DIR}
- bash buildscripts/asciidoc/create_mermaid_config.sh
install:
- gem install asciidoctor -v 1.5.8
- gem install asciidoctor-diagram -v 1.5.14
- gem install asciidoctor-pdf --pre
- gem install rouge
- gem install concurrent-ruby
- npm install -g inline-source-cli
- npm install --save cheerio lunr asciidoctor.js minimist
- npm install -g mermaid.cli
script:
- travis_wait bash buildscripts/build.sh
deploy:
- provider: s3
  access_key_id: "$S3ACCESSID"
  secret_access_key: "$S3ACCESSKEY"
  bucket: wirecard-docs-internal
  region: eu-central-1
  skip_cleanup: true
  local-dir: build/html
  on:
    branch: staging
- provider: s3
  access_key_id: "$S3ACCESSID"
  secret_access_key: "$S3ACCESSKEY"
  bucket: wirecard-docs
  region: eu-central-1
  skip_cleanup: true
  local-dir: build/html
  on:
    branch: master
