language: ruby
install:
  - gem install asciidoctor
  - gem install asciidoctor-diagram
  - gem install asciidoctor-pdf --pre
  - gem install rouge
  - gem install concurrent-ruby
  - npm install -g inline-source-cli
  - npm install --save cheerio
  - npm install --save lunr
script:
  - mkdir -p build/html/css
  - cp css/font-awesome*.css build/html/css
  - cp -r images js fonts build/html/
  - bash buildscripts/tests/basic-tests.sh
  - RUBYOPT="-E utf-8" asciidoctor -b html5 --failure-level=WARN -a systemtimestamp=$(date +%s) -a toc=left -a docinfo=shared -a icons=font -r asciidoctor-diagram index.adoc -o index.html
  - cp index.html custom-mode.html
  - node buildscripts/split-pages/create-toc.js
  - node buildscripts/search/lunr-index-builder.js
  - RUBYOPT="-E utf-8" asciidoctor -b multipage_html5 --failure-level=WARN -a systemtimestamp=$(date +%s) -a toc=left -a docinfo=shared -a icons=font -r asciidoctor-diagram -r ./buildscripts/asciidoc/multipage-html5-converter.rb index.adoc
  - mv toc.json searchIndex.json *.html build/html/
  - mv errorpages/* build/html/
deploy:
    provider: s3
    access_key_id: $S3ACCESSID
    secret_access_key: $S3ACCESSKEY
    bucket: wirecard-docs-internal
    region: eu-central-1
    skip_cleanup: true
    local-dir: build/html
    on:
      branch: staging
