language: php
php: 7.2
git:
  depth: false
before_script:
- INIT_DIR=$(pwd)
install:
- gem install asciidoctor -v 1.5.8
script:
- echo "Test Me"
notifications:
  slack:
    secure: xPHxCl9vnZe9Ljg47fKcRXJRf40GKIoIbNkaZ2Abp2ICCdh+W1xMKZ4mrRCgALMy5ojtnomnRvlMxphBNfkE125l/Pe6st8RH2MbiGH+glDi+RoiCAJWoBg98Q66+yQMXuLrjhIkCANgrZ3x+/GpYR4z0/FBPdnNzwkM/ZDr3NvpDUvLX6wzLM9YruYGsJ1lmENJBOJuIOzn5S/I8b98WB9H6hRKemgVE9ZRb0BxeEPmF123lXSy39bLMMhV8CuoRrx5MlYkGu4Et/5m+9beDQhJetExUKmrpe1c/JLsg+8CMlyruAw8hIUnd/hByooaoi+lTzxnfOs558i1AgCJ+fJSVqpTTVrzDbz0kRwfzgCp376AWW385k9mX5IBmIPrDwnatFHOBzV5Tj1A58IaDrPtXedEgwpamadmx6BncGQSD2flHwdjmfi9Max5680G00Qtbd8SbYS0WP/ECtKYQmPDdlqU1ExO/Z7n2gxSjVIy1aDtyzwlFIo/Rb+ury7a5nu6TO8IDZKcSO/cZ0VIL+rKDbeWN8g7UBYJWQDg82WEtqF/fpiRUZbrlaT0VnczMnNCHdCttUxLF9QHqCsgo+DltHYQUh7q1Ol8u1ZE+47s9+Usd1MnvjOAQjYUV4jV4JgWfvJG1GNYvLs9hCJ7dXDUPbYL5PW30YFA02uKll8=
    on_success: always
