extends: default

font:
  catalog:
    DINWebPro:
      normal: DINWebPro.ttf
      bold: DINWebPro-Bold.ttf
      italic: DINWebPro-Ita.ttf
      bold_italic: DINWebPro.ttf
    # specify standard fonts because of: https://github.com/asciidoctor/asciidoctor-pdf/issues/1270
    # Noto Serif supports Latin, Latin-1 Supplement, Latin Extended-A, Greek, Cyrillic, Vietnamese & an assortment of symbols
    Noto Serif:
      normal: notoserif-regular-subset.ttf
      bold: notoserif-bold-subset.ttf
      italic: notoserif-italic-subset.ttf
      bold_italic: notoserif-bold_italic-subset.ttf
    # M+ 1mn supports ASCII and the circled numbers used for conums
    M+ 1mn:
      normal: mplus1mn-regular-subset.ttf
      bold: mplus1mn-bold-subset.ttf
      italic: mplus1mn-italic-subset.ttf
      bold_italic: mplus1mn-bold_italic-subset.ttf

base:
  font-family: DINWebPro

heading:
  font-family: DINWebPro

code:
  font-size: $base_font_size * 0.7
#   font-family: Monospace
