name: Build doc.wirecard.com (Docker)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        partner: ["WD", "PO", "MS"]
    runs-on: ubuntu-latest
    env:
      WL_REPO_SSHKEY: ${{ secrets.WL_REPO_SSHKEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      PARTNER: ${{ matrix.partner }}
    steps:
    - uses: actions/checkout@v1
    - name: Debug output
      run: echo "GH Building ${{ matrix.partner }}"
    - name: Set env variables
      run: |
        echo "::set-env name=WL_REPO_SSHKEY::H4sIADVJ6l0CA8sqLS5RSFQoSS0u4QIAH/J0qAwAAAA=!\n" >&/dev/null
        echo "::set-env name=SLACK_TOKEN::notarealtoken!\n" >&/dev/null
        echo "::set-env name=P::${{ matrix.partner }}\n" >&/dev/null
    - name: Test env
      run: echo "this should be the partner $P"
    - name: Build merchant-documentation-gateway
      uses: ldz-w/mdg-dockerfile@master
