name: Build doc.wirecard.com (Docker)

on: [push, pull_request]

jobs:
  build:
    steps:
    - name: Build
      uses: ldz-w/mdg-dockerfile@master
      env:
        WL_REPO_SSHKEY: ${{ secrets.WL_REPO_SSHKEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

