name: Build doc.wirecard.com (Docker)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
          - {partner: "WD", bucket: "wirecard-docs", deploy: false}
          - {partner: "PO", bucket: "p-bckt", deploy: false}
          - {partner: "MS", bucket: "m-bckt", deploy: false}

    runs-on: ubuntu-latest
    env:
      WL_REPO_SSHKEY: ${{ secrets.WL_REPO_SSHKEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      PARTNER: ${{ matrix.config.partner }}
    steps:
    - uses: actions/checkout@v1
    - name: Build merchant-documentation-gateway
      uses: ldz-w/mdg-dockerfile@master

    - name: Set default environment
      run: |
        echo "::set-env name=ENVIRONMENT::internal"
        echo "::set-env name=BRANCH::${GITHUB_REF##*/}"
        echo "::set-env name=DEPLOY_DIR::${GITHUB_REF##*/}"
        echo "::set-env name=BUCKET::${{ matrix.config.bucket }}-internal"
        echo "::set-env name=NBUCKET::n-bckt-internal"
    - name: Set environment (production)
      if: endsWith(github.ref, '/master')
      run: |
        echo "::set-env name=ENVIRONMENT::production"
        echo "::set-env name=DEPLOY_DIR::/"
        echo "::set-env name=BUCKET::${{ matrix.config.bucket }}"
        echo "::set-env name=NBUCKET::n-bckt"
    - name: Set environment (staging)
      if: endsWith(github.ref, '/staging')
      run: |
        echo "::set-env name=ENVIRONMENT::staging"
        echo "::set-env name=DEPLOY_DIR::/"

    - name: Debug env
      run: |
        echo "${{ env.ENVIRONMENT }}"
        echo "${{ env.BRANCH }}"
        echo "${{ env.DEPLOY_DIR }}"
        echo "${{ env.BUCKET }}"
        echo "${{ env.NBUCKET }}"

    - name: Deploy doc.wirecard.com
      if: matrix.config.deploy
      uses: wirecard/s3-deploy@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRETS_ACCESS_KEY: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ env.BUCKET }}
        SRC_DIR: ${{ env.PARTNER }}-html
        DST_DIR: ${{ env.DEPLOY_DIR }}

    - name: Deploy NOVA
      if: env.PARTNER == 'WD' && matrix.config.deploy
      uses: wirecard/s3-deploy@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRETS_ACCESS_KEY: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ env.NBUCKET }}
        SRC_DIR: NOVA-html
        DST_DIR: ${{ env.DEPLOY_DIR }}
