name: Build doc.wirecard.com (Docker)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        partner: ["WD", "PO", "MS"]
    runs-on: ubuntu-latest
    env:
      WL_REPO_SSHKEY: ${{ secrets.WL_REPO_SSHKEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      PARTNER: ${{ matrix.partner }}
    steps:
    - uses: actions/checkout@v1
    - name: Debug output
      run: echo "GH Building ${{ matrix.partner }}"
    - name: Build merchant-documentation-gateway
      uses: ldz-w/mdg-dockerfile@master
