name: doc.wirecard.com

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - env:
      - WL_REPO_SSHKEY: ${{ secrets.WL_REPO_SSHKEY }}
      - SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: Set up Node.js v10.x
      uses: actions/setup-node@v1
      with:
        node-version: v10.x
    - name: Install Node.js dependencies
      run: npm install

    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Python 3 dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build docs
      run: bash buildscripts/main.sh

