name: doc.wirecard.com

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: Set up Node.js v10.x
      uses: actions/setup-node@v1
      with:
        node-version: v10.x
      run: npm install

    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build docs
      uses: actions/checkout@v1
      run: bash buildscripts/main.sh

